# ========================================================================== #
#         CONFIGURAÇÃO DOCKER COMPOSE PARA O AMBIENTE DE DESENVOLVIMENTO     #
# ========================================================================== #
# Este arquivo orquestra a aplicação Docker multi-contêiner. Ele define
# os serviços (como a API e, futuramente, um banco de dados), as redes e
# os volumes necessários para executar a pilha completa da aplicação.
#

services:
  api:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
