"""Add timezone to PasswordResetToken

Revision ID: 71eb90191d58
Revises: dc74f7fab342
Create Date: 2025-06-25 13:49:11.469878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71eb90191d58'
down_revision: Union[str, Sequence[str], None] = 'dc74f7fab342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
