"""add coupon and discount functionality

Revision ID: a04e370723d1
Revises: c538439d9c89
Create Date: 2025-06-26 13:20:42.566755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04e370723d1'
down_revision: Union[str, Sequence[str], None] = 'c538439d9c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('coupon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'carts', 'coupons', ['coupon_id'], ['id'])
    op.add_column('orders', sa.Column('discount_amount', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('coupon_code_used', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'coupon_code_used')
    op.drop_column('orders', 'discount_amount')
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_column('carts', 'coupon_id')
    # ### end Alembic commands ###
